spring: 
  profiles: 
  active: 
  - dev
---
spring: 
  profiles: dev #开发环境
  application: 
    name: microservicecloud-config-yancy-dev
---
spring: 
  profiles: test #测试环境
  application:  
    name: microservicecloud-config-yancy-test
# 请保存为UTF-8格式